### ISSUE TITLE
Composer path is not defined

### ISSUE THREAD

**Issue by o10g** [ansible-roles/ansible-role-symfony2#2]
After I fixed previous issues I got next error:

> fatal: [instamagnet.by] => One or more undefined variables: 'composer_path' is undefined

And it's weird, as you wrote, that if composer is not present on system it will be automaticaly downloaded.

**Comment by igormukhingmailcom** [comment]
Hi.
Role is under development right now. Some features disabled, other may have bugs, etc.

As a workaround, you can use `kosssi.composer` role right before this one.
I think that I will remove any comments about `Install if not present` feature for composer. Because there are no significant reason to implement this inside `symfony2` role.

**Comment by o10g** [comment]
Thank you for your feedback.
I tried to uncomment the composer feature and noticed that it works for now :)

By the way, thank you for the recommendation of kosssi.composer role. I'll take a look.

**Comment by igormukhingmailcom** [comment]
Fixed.
